name: Test After PullRequest

on:
  pull_request: {}

jobs:
  setup:
    runs-on: windows-latest

    outputs:
      id: ${{ steps.setup.outputs.id }}

    steps:
    - name: Checkout code
      id: setup
      uses: actions/checkout@v2
    
    - name: Restore NuGet Packages
      run: nuget restore BardCore.sln
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

  build-and-test-cpp:
    needs: setup
    runs-on: windows-latest
    
    strategy:
      matrix:
        cpp-version: [14, 17]

    steps:
    - name: Build C++ BardCore Release (Cpp-${{ matrix.cpp-version }})
      run: |
        msbuild /t:Build /p:Configuration=Release-${{ matrix.cpp-version }} /p:Platform=x64 BardCore.sln
      working-directory: ${{ github.workspace }}
      
    - name: Run C++ Tests Release (Cpp-${{ matrix.cpp-version }})
      run: |
        ./x64/release-${{ matrix.cpp-version }}/Tests.exe
