name: Nuget Package Upload

on:
  pull_request: {}
  
jobs:
  nuget_package_upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NuGet Packages
        run: nuget restore BardCore.sln
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build C++ BardCore Release
        run: |
          msbuild /t:Build /p:Configuration=Release /p:Platform=x64 BardCore.sln
        working-directory: ${{ github.workspace }}

      - name: Install Nuget
        run: |
          curl -s https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      - name: Get Last Version
        run: |
          $NUGET_VERSION = (nuget list BardCore) -replace "BardCore ",''
          nuget list BardCore
          echo $NUGET_VERSION
        shell:
          powershell
          
      - name: Make Package
        run: nuget pack Bardcore/nuget/bardcore.nuspec -p Version=${{ vars.NUGET_VERSION }} -p ReleaseNotes="Automatic release"

      - name: Update NUGET_VERSION
        run: |
          $lastNumber = $NUGET_VERSION.Split('.')[-1]
          
          $NUGET_VERSION = $NUGET_VERSION -replace "\.\d+$", ""
          
          $NUGET_VERSION += $lastNumber
          echo $NUGET_VERSION

        shell: 
          powershell
