name: Nuget Package Upload

on:
  pull_request: {}
  
jobs:
  build_and_run:
    runs-on: windows-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NuGet Packages
        run: nuget restore BardCore.sln
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build C++ BardCore Release
        run: |
          msbuild /t:Build /p:Configuration=Release /p:Platform=x64 BardCore.sln
        working-directory: ${{ github.workspace }}

      - name: Install Nuget
        run: |
          curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    
      - name: Make Package
        run: nuget pack Bardcore/nuget/bardcore.nuspec -p Version=${{ vars.NUGET_VERSION }} -p ReleaseNotes="Automatic release"
          
      - name: Secret
        run: |
          setlocal enabledelayedexpansion
          set "NEW_NUGET_VERSION=${{ vars.NUGET_VERSION }}"
          
          rem Extract the last part (the build number) from the version
          for /f "tokens=3 delims=." %%a in ("!NEW_NUGET_VERSION!") do set "BUILD_NUMBER=%%a"
          
          set /a "NEW_BUILD_NUMBER=BUILD_NUMBER + 1"
          
          set "NUGET_VERSION=!NEW_NUGET_VERSION:%BUILD_NUMBER%=%NEW_BUILD_NUMBER%!"
          echo "NUGET_VERSION=$NEW_NUGET_VERSION" >> $GITHUB_ENV
          endlocal
    
        
